# Generated by Django 5.0.6 on 2024-06-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_userprofile_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Food_items', models.CharField(max_length=255, verbose_name='Food_items')),
                ('Breakfast', models.BinaryField(verbose_name='Breakfast')),
                ('Lunch', models.BinaryField(verbose_name='Lunch')),
                ('Dinner', models.BinaryField(verbose_name='Dinner')),
                ('VegNonVeg', models.BinaryField(verbose_name='VegNonVeg')),
                ('Calories', models.FloatField(verbose_name='Calories')),
                ('Fats', models.FloatField(verbose_name='Fats')),
                ('Proteins', models.FloatField(verbose_name='Proteins')),
                ('Iron', models.FloatField(verbose_name='Iron')),
                ('Calcium', models.FloatField(verbose_name='Calcium')),
                ('Sodium', models.FloatField(verbose_name='Sodium')),
                ('Potassium', models.FloatField(verbose_name='Potassium')),
                ('Carbohydrates', models.FloatField(verbose_name='Carbohydrates')),
                ('Fibre', models.FloatField(verbose_name='Fibre')),
                ('VitaminD', models.FloatField(verbose_name='VitaminD')),
                ('Sugars', models.FloatField(verbose_name='Sugars')),
            ],
        ),
    ]
